#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NaitonGPS.Droid.Resource", IsApplication=true)]

namespace NaitonGPS.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int acceptance = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int back = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int back2 = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int bell = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int bellNotification = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int btnPopup = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int chat = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int chat2x = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int chatGreen = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int chatWhite = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int closePopup = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int compass = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int compass2x = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int compassGreen = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int compassWhite = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int crossdock = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int delivery = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int deliveryWhite = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int dispatch = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int home = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int home2x = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int homeGreen = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int homeWhite = 2130837526;
			
			// aapt resource value: 0x7F020019
			public const int icon_about = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int icon_feed = 2130837530;
			
			// aapt resource value: 0x7F020017
			public const int ic_eye = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int ic_eye_hide = 2130837528;
			
			// aapt resource value: 0x7F02001B
			public const int lblPrint = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int leftarrow = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int leftarrowWhite = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int logoMain = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int logoNaiton = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int logoNaitonNavbar = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int logoNavbar = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int lorry = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int minus = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int more = 2130837540;
			
			// aapt resource value: 0x7F020025
			public const int more2x = 2130837541;
			
			// aapt resource value: 0x7F020026
			public const int moreoptions = 2130837542;
			
			// aapt resource value: 0x7F020027
			public const int nonLogo = 2130837543;
			
			// aapt resource value: 0x7F020028
			public const int notFound = 2130837544;
			
			// aapt resource value: 0x7F020029
			public const int notFoundGreen = 2130837545;
			
			// aapt resource value: 0x7F02002A
			public const int notFoundWhite = 2130837546;
			
			// aapt resource value: 0x7F02002B
			public const int notification = 2130837547;
			
			// aapt resource value: 0x7F02002C
			public const int notificationWhite = 2130837548;
			
			// aapt resource value: 0x7F02002D
			public const int packageGreen = 2130837549;
			
			// aapt resource value: 0x7F02002E
			public const int picklist = 2130837550;
			
			// aapt resource value: 0x7F02002F
			public const int plus = 2130837551;
			
			// aapt resource value: 0x7F020030
			public const int question = 2130837552;
			
			// aapt resource value: 0x7F020031
			public const int reform = 2130837553;
			
			// aapt resource value: 0x7F020032
			public const int rightarrow = 2130837554;
			
			// aapt resource value: 0x7F020033
			public const int rightarrowWhite = 2130837555;
			
			// aapt resource value: 0x7F020034
			public const int scan = 2130837556;
			
			// aapt resource value: 0x7F020035
			public const int search = 2130837557;
			
			// aapt resource value: 0x7F020036
			public const int settings = 2130837558;
			
			// aapt resource value: 0x7F020037
			public const int settingsWhite = 2130837559;
			
			// aapt resource value: 0x7F020038
			public const int statusBar = 2130837560;
			
			// aapt resource value: 0x7F020039
			public const int technology = 2130837561;
			
			// aapt resource value: 0x7F02003A
			public const int userInformation = 2130837562;
			
			// aapt resource value: 0x7F02003B
			public const int userWhite = 2130837563;
			
			// aapt resource value: 0x7F02003C
			public const int validation = 2130837564;
			
			// aapt resource value: 0x7F02003D
			public const int vehicle = 2130837565;
			
			// aapt resource value: 0x7F02003E
			public const int vehicleGreen = 2130837566;
			
			// aapt resource value: 0x7F02003F
			public const int vehicleWhite = 2130837567;
			
			// aapt resource value: 0x7F020040
			public const int xamarin_logo = 2130837568;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F030001
			public const int icon = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int icon_round = 2130903042;
			
			// aapt resource value: 0x7F030000
			public const int ic_launcher = 2130903040;
			
			// aapt resource value: 0x7F030003
			public const int launcherIcon = 2130903043;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F040000
			public const int MainTheme = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
